import { Outfit } from "next/font/google";
import "./globals.css";


const outfit = Outfit({
  subsets: ['latin'], // Specify subsets
  weight: ['400', '700'], // Specify weights if not using a variable font
  display: 'swap', // Optional: controls font display behavior
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body
        className={`${outfit.className}  antialiased`}
      >

        {children}
      </body>
    </html>
  );
}
